{
 "title": "Fabric Health",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "time()*1000000000-gnmic_boot_time_boot_time",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_intf_config_ip{job=\"gnmic\", interface_name=\"Management0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory utilized",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gnmic_memory_utilized{job=\"gnmic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "gnmic_cpu_avg{job=\"gnmic\"}",
     "legendFormat": "{{source}}/{{component_name}}"
    }
   ]
  }
 ]
}