{
 "title": "Interface Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Intf Admin Status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values by() (\"count\", gnmic_intf_admin_state_admin_status{job=\"gnmic\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Intf Oper State",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values by() (\"count\", gnmic_intf_oper_state_oper_status{job=\"gnmic\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EOS Versions",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "gnmic_show_ver_version{job=\"gnmic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Admin Status Table",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "gnmic_intf_admin_state_admin_status{job=\"gnmic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface traffic stats (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(gnmic_intf_ctrs_in_octets[$__rate_interval])",
     "legendFormat": "{{source}}//{{interface_name}} - In"
    },
    {
     "expr": "rate(gnmic_intf_ctrs_out_octets[$__rate_interval])",
     "legendFormat": "{{source}}//{{interface_name}} - Out"
    }
   ]
  },
  {
   "title": "Interface Discards per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(gnmic_intf_ctrs_in_discards[$__rate_interval])",
     "legendFormat": "{{source}}//{{interface_name}} - In"
    },
    {
     "expr": "rate(gnmic_intf_ctrs_out_discards[$__rate_interval])",
     "legendFormat": "{{source}}//{{interface_name}} - Out"
    }
   ]
  }
 ]
}